env:
  es6: true
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: {
    "@typescript-eslint/no-var-requires": off,
    "@typescript-eslint/no-unused-vars": off,
  }
settings:
  import/resolver:
    node:
      extensions: [".ts"]
